[package]
authors = ["Anisuzzaman Khan <aniskhan001@yahoo.com>"]
name = "rust-gem"
version = "0.1.0"

[dependencies]
diesel = {version = "1.4.5", features = ["mysql"]}
mysql = "18.2.0"
mysqlclient-sys = "0.2.4"
r2d2 = "0.8.8"
r2d2-diesel = "1.0.0"
rocket = "0.4.4"
rocket_codegen = "0.4.4"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.62"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
version = "*"
