[package]
name = "rust-gem"
version = "0.1.0"
authors = ["Anisuzzaman Khan <aniskhan001@yahoo.com>"]

[dependencies]
rocket = "0.4.4"
rocket_codegen = "0.4.4"
serde = "1.0.113"
serde_json = "1.0.55"
serde_derive = "1.0.112"
mysql = "18.2.0"
diesel = { version = "1.4.5", features = ["mysql"] }
r2d2 = "0.8.8"
r2d2-diesel = "1.0.0"
mysqlclient-sys = "0.2.4"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
