[package]
name = "rust-gem"
version = "0.1.0"
authors = ["Anisuzzaman Khan <aniskhan001@yahoo.com>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
serde = "1.0.71"
serde_json = "1.0.24"
serde_derive = "1.0.71"
mysql = "14.0.0"
diesel = { version = "1.3.2", features = ["mysql"] }
r2d2 = "*"
r2d2-diesel = "*"
mysqlclient-sys = "0.2.3"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
